### ISSUE TITLE
Error not being thrown if git repo doesn't exist.

### ISSUE THREAD

**Issue by ispyinternet** [strugee/node-git-clone-or-pull#12]

**Comment by strugee** [comment]
@ispyinternet thanks for filing this - it caused me to fix a bunch of bugs in the test suite :)

However I couldn't reproduce your problem locally, and all the related tests are passing. Please post all the relevant information, including Node version, the backend you're using, the version of git-clone-or-pull you're using, and `npm ls smart-spawn`.

Unless you really did mean "thrown"? This module will _never_ intentionally throw errors; instead, it'll pass the error in the callback. Does this need to be clarified in the docs?

**Comment by ispyinternet** [comment]
So im not sure how the package works, but it looks like due to a space in the directory name nodegit wasn't configuring libssh properly on the install hook. Nevertheless I was able to clone... (? some fallback ?) Anyway after noticing and fixing this I am now seeing thrown errors, however, I am unable to clone with a nodegit error:  'authentication required but no callback set'. Reading nodegit looks like I need an option:  { ignoreCertErrors: 1}. Do you pass through options like this?  

ok just read about the fallback implementations: nodegit / subprocess. So in the case of subprocess I suspect its not throwing errors correctly?

and I see you pass nodegit options through the second param...

hmm, appears I can trap the error now with subprocess:

Error: Process `git clone --quiet --branch master xxxx exited with non-zero exit code 128; stderr is:
Repository not found

Not sure. Im closing.
